import "./globals.css";

import type { Metadata } from "next";
import Navbar from "../components/Navbar/navbar";
import Providers from "@/components/Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col bg-background text-foreground">
        <Providers>
          <Navbar />
          <main className="container flex flex-grow flex-col">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
